apiVersion: v1
kind: Service
metadata:
  name: enclave-runner-service
spec:
  type: NodePort
  selector:
    app: enclave-runner-container
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
