# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmyservice.proto\x12\tmyservice\"5\n\x0e\x45xecuteRequest\x12\x10\n\x08\x66unction\x18\x01 \x01(\x0c\x12\x11\n\targuments\x18\x02 \x01(\x0c\"!\n\x0f\x45xecuteResponse\x12\x0e\n\x06result\x18\x01 \x01(\x0c\x32O\n\tMyService\x12\x42\n\x07\x45xecute\x12\x19.myservice.ExecuteRequest\x1a\x1a.myservice.ExecuteResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myservice_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EXECUTEREQUEST']._serialized_start=30
  _globals['_EXECUTEREQUEST']._serialized_end=83
  _globals['_EXECUTERESPONSE']._serialized_start=85
  _globals['_EXECUTERESPONSE']._serialized_end=118
  _globals['_MYSERVICE']._serialized_start=120
  _globals['_MYSERVICE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
